back-end/GraeyCarWash/GraeyCarWash/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('washers/', include('wash.urls', namespace='wash')),
    path('', include('user.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back-end/GraeyCarWash/user/urls.py
# from django.contrib.auth.views import LoginView
from django.urls import path

from user.views import user_registration, user_login, user_logout

app_name = 'user'

urlpatterns = [
    # path('', LoginView.as_view(
    #     template_name='user/login.html'
    # ), name='user_login'),
    path('', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('registration/', user_registration, name='user_registration'),
]

back-end/GraeyCarWash/wash/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class CarType(models.Model):
    name = models.CharField(max_length=45, verbose_name=_('Car Type'), unique=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)

    def __str__(self):
        return self.name


class WashType(models.Model):
    name = models.CharField(max_length=45, verbose_name=_('Car Type'), unique=True)
    percentage = models.IntegerField(verbose_name=_("Percentage of base price"), default=100)

    def __str__(self):
        return self.name


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    expiration_date = models.DateTimeField(verbose_name=_('Coupon Expiration Date'), null=True, blank=True)
    discount = models.IntegerField(verbose_name=_('Discount'), help_text='%')
    quantity = models.IntegerField(verbose_name=_('Quantity'), default=1)
    car_plate = models.CharField(max_length=20, verbose_name=_("Car's license plate"))

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = _('Coupon')
        verbose_name_plural = _('Coupons')


class Car(models.Model):
    car_type = models.ForeignKey(
        to='CarType',
        on_delete=models.SET_NULL,
        null=True, related_name='cars'
    )
    licence_plate = models.CharField(max_length=20, verbose_name=_("License plate"))

    def __str__(self):
        return self.licence_plate

    class Meta:
        verbose_name = _('Car')
        verbose_name_plural = _('Cars')


class Order(models.Model):
    car = models.ForeignKey(
        to='Car', related_name='orders',
        on_delete=models.PROTECT,
    )
    employee = models.ForeignKey(
        to='user.User', on_delete=models.SET_NULL,
        null=True, related_name='orders',
    )
    # @TODO: washer_percentage
    coupon = models.ForeignKey(
        to='Coupon', related_name='orders',
        on_delete=models.PROTECT,
        null=True, blank=True,
    )
    wash_type = models.ForeignKey(
        to='WashType', related_name='orders',
        on_delete=models.PROTECT,
    )

    note = models.TextField(null=True, blank=True, verbose_name=_("Note"))
    price = models.DecimalField(max_digits=4, decimal_places=2, verbose_name=_("Price"))

    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Created date"))
    start_date = models.DateTimeField(verbose_name=_('Scheduled time'))
    end_date = models.DateTimeField(verbose_name=_('End time'), blank=True, null=True)

    def __str__(self):
        return f'{self.car} using {self.wash_type}'

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def save(self, *args, **kwargs):
        if not self.pk:
            self.price = self.car.car_type.price * self.wash_type.percentage / 100
        super(Order, self).save(*args, **kwargs)

back-end/GraeyCarWash/templates/components/order-form.html
{#                <form class="col s12" enctype="multipart/form-data">#}
<form action="." class="col s12" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="input-field col s6">
            {{ form.car }}
            <label for="id_car">Choose a car:</label>
            {% for error in form.errors.car %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="input-field col s6">
            {{ form.wash_type }}
            <label for="id_wash_type">Choose a wash type:</label>
            {% for error in form.errors.wash_type %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="input-field col s6">
{#            <i class="material-icons prefix">mode_edit</i>#}
            {{ form.start_date_day }}
            <label for="id_start_date_day">Note</label>
            {% for error in form.errors.start_date_day %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="input-field col s6">
{#            <i class="material-icons prefix">mode_edit</i>#}
            {{ form.start_date_time }}
            <label for="id_start_date_time">Note</label>
            {% for error in form.errors.start_date_time %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12">
            <i class="material-icons prefix">mode_edit</i>
            {{ form.note }}
            <label for="id_note">Note</label>
            {% for error in form.errors.note %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col s12 center">
            <button class="btn waves-effect waves-light" type="submit" name="action">გაგზავნა
                <i class="material-icons right">send</i>
            </button>
        </div>
    </div>
</form>

<style>
    .error{
        color: red;
    }
</style>