back-end/GraeyCarWash/GraeyCarWash/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('washers/', include('wash.urls', namespace='wash')),
    path('', include('user.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back-end/GraeyCarWash/user/urls.py
# from django.contrib.auth.views import LoginView
from django.urls import path

from user.views import user_registration, user_login, user_logout

app_name = 'user'

urlpatterns = [
    # path('', LoginView.as_view(
    #     template_name='user/login.html'
    # ), name='user_login'),
    path('', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('registration/', user_registration, name='user_registration'),
]

back-end/GraeyCarWash/user/models.py
from decimal import Decimal

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.validators import validate_email
from django.db import models
from django.db.models import IntegerChoices
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        validate_email(email)
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        # extra_fields.setdefault('is_active', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('birthdate', timezone.now())
        extra_fields.setdefault('image', "profiles/placeholder.jpg")
        extra_fields.setdefault('salary', 0)
        extra_fields.setdefault('phone_number', '0')
        extra_fields.setdefault('status', 3)
        extra_fields.setdefault('hire_date', timezone.now())
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    birthdate = models.DateField(verbose_name=_('Birth Date'), )
    image = models.ImageField(verbose_name=_("Image"), upload_to='profiles')
    salary = models.DecimalField(
        max_digits=8, decimal_places=2,
        verbose_name=_('Salary'), help_text='in Lari / % (if being washer )',
        default=Decimal(0)  # @TODO: Optimize
    )
    phone_number = models.CharField(max_length=50, verbose_name=_('Phone Number'))
    hire_date = models.DateField(auto_now_add=True, verbose_name=_("Hire Date"))

    class Status(IntegerChoices):
        customer = 1, _("Customer")
        washer = 2, _("Washer")
        manager = 3, _("Manager")

    status = models.PositiveSmallIntegerField(choices=Status.choices)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.get_full_name()

    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')

    def get_absolute_url(self):
        return reverse('wash:washer-detail', kwargs={'pk': self.pk})

back-end/GraeyCarWash/user/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from user.models import User


class CustomUserCreationForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    birthdate = forms.DateField(widget=forms.TextInput(attrs={
        'class': 'datepicker'
    }))

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'birthdate',
            'image',
            'phone_number',
            'password1',
            'password2'
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password2')
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error('password2', error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

back-end/GraeyCarWash/user/views.py
from django.conf import settings
from django.contrib.auth import login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect

from user.forms import CustomUserCreationForm
from user.models import User
from django.contrib.auth.forms import AuthenticationForm


def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)
    return HttpResponse(status=405)


def user_login(request):
    if request.user.is_authenticated:
        return redirect('wash:washer-list')
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('wash:washer-list')

    return render(
        request,
        'user/login.html',
        context={
            'form': form
        }
    )


def user_registration(request):
    user_create_form = CustomUserCreationForm()
    if request.method == 'POST':
        user_create_form: CustomUserCreationForm = CustomUserCreationForm(request.POST, files=request.FILES)
        if user_create_form.is_valid():
            customer: User = user_create_form.save(commit=False)
            customer.status = User.Status.customer
            customer.save()
            return redirect('user:user_login')

    return render(
        request,
        template_name='user/registration.html',
        context={
            'form': user_create_form
        }
    )

back-end/GraeyCarWash/templates/user/login.html
{% extends 'base.html' %}



{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12">
                <form class="col s12" action="{% url 'user:user_login' %}" method="POST" autocomplete="off" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">
                            {{ form.username }}
                            <label for="{{ form.username.id_for_label }}">Email</label>
                            {% for error in form.errors.username %}
                                <p class="error">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            {{ form.password }}
                            <label for="{{ form.password.id_for_label }}">Password</label>
                            {% for error in form.errors.password %}
                                <p class="error">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    {{ form.errors }}
                    <div class="row">
                        <div class="col s12 center">
                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                ავტორიზაცია
                                <i class="material-icons right">login</i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <a href="{% url "user:user_registration" %}">რეგისტრაცია</a>
            </div>
        </div>
    </div>
{% endblock %}

back-end/GraeyCarWash/templates/user/registration.html
{% extends 'base.html' %}



{% block content %}
<div class="container pt-30">
    <div class="section">
        <div class="row">
            <div class="col s12">
                <form class="col s12" action="{% url 'user:user_registration' %}" method="POST" enctype="multipart/form-data" autocomplete="off" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col m6 s12">
                            {{ form.first_name}}
                            <label for="id_first_name">First Name</label>
                            {% for error in form.errors.first_name %}
                                <p class="error">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="input-field col m6 s12">
                            {{ form.last_name}}
                            <label for="id_last_name">Last Name</label>
                            {% for error in form.errors.last_name %}
                                <p class="error">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m6 s12">
                            <div class="row">
                                <div class="input-field col s12">
                                    {{ form.email }}
                                    <label for="id_email">Email</label>
                                    {% for error in form.errors.email %}
                                        <p class="error">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    {{ form.phone_number }}
                                    <label for="id_phone_number">Phone</label>
                                    {% for error in form.errors.phone_number %}
                                        <p class="error">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="col m6 s12">
                            <div class="row">
                                <div class="col s12 center">
                                    {{ form.image }}
                                    <label for="{{ form.image.id_for_label }}" class="btn waves-effect waves-light">
                                        სურათის ატვირთვა
                                        <i class="material-icons right">upload</i>
                                    </label>
                                    {% for error in form.errors.image %}
                                        <p class="error">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12 center">
                                    {{ form.birthdate }}
                                    <label for="{{ form.birthdate.id_for_label }}">Birthdate</label>
                                    {% for error in form.errors.birthdate %}
                                        <p class="error">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col m6 s12">
                            {{ form.password1 }}
                            <label for="{{ form.password1.id_for_label }}">Password</label>
                            {% for error in form.errors.password1 %}
                                <p class="error">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="input-field col m6 s12">
                            {{ form.password2 }}
                            <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
                            {% for error in form.errors.password2 %}
                                <p class="error">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12 center">
                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                რეგისტრაცია
                                <i class="material-icons right">send</i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="section">
        <div class="row">
            <div class="col s12 center">
                <a href="{% url 'user:user_login' %}">უკვე რეგისტრირებული ხარ?</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block style %}
    <style>
        #id_image{
            display: none;
        }
    </style>
{% endblock %}