back-end/GraeyCarWash/GraeyCarWash/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('washers/', include('wash.urls', namespace='wash')),
    path('', include('user.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back-end/GraeyCarWash/user/urls.py
# from django.contrib.auth.views import LoginView
from django.urls import path

from user.views import user_registration, user_login, user_logout

app_name = 'user'

urlpatterns = [
    # path('', LoginView.as_view(
    #     template_name='user/login.html'
    # ), name='user_login'),
    path('', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('registration/', user_registration, name='user_registration'),
]

back-end/GraeyCarWash/wash/urls.py
from django.contrib.auth.decorators import login_required as lr
from django.urls import path

from wash.views import washer_list_view, WasherDetail

app_name = 'wash'

urlpatterns = [
    path('', lr(washer_list_view), name='washer-list'),
    path('<int:pk>/', WasherDetail.as_view(), name='washer-detail'),
]

back-end/GraeyCarWash/wash/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class CarType(models.Model):
    name = models.CharField(max_length=45, verbose_name=_('Car Type'), unique=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)

    def __str__(self):
        return self.name


class WashType(models.Model):
    name = models.CharField(max_length=45, verbose_name=_('Car Type'), unique=True)
    percentage = models.IntegerField(verbose_name=_("Percentage of base price"), default=100)

    def __str__(self):
        return self.name


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    expiration_date = models.DateTimeField(verbose_name=_('Coupon Expiration Date'), null=True, blank=True)
    discount = models.IntegerField(verbose_name=_('Discount'), help_text='%')
    quantity = models.IntegerField(verbose_name=_('Quantity'), default=1)
    car_plate = models.CharField(max_length=20, verbose_name=_("Car's license plate"))

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = _('Coupon')
        verbose_name_plural = _('Coupons')


class Car(models.Model):
    car_type = models.ForeignKey(
        to='CarType',
        on_delete=models.SET_NULL,
        null=True, related_name='cars'
    )
    licence_plate = models.CharField(max_length=20, verbose_name=_("License plate"))

    def __str__(self):
        return self.licence_plate

    class Meta:
        verbose_name = _('Car')
        verbose_name_plural = _('Cars')


class Order(models.Model):
    car = models.ForeignKey(
        to='Car', related_name='orders',
        on_delete=models.PROTECT,
    )
    employee = models.ForeignKey(
        to='user.User', on_delete=models.SET_NULL,
        null=True, related_name='orders',
    )
    # @TODO: washer_percentage
    coupon = models.ForeignKey(
        to='Coupon', related_name='orders',
        on_delete=models.PROTECT,
        null=True, blank=True,
    )
    wash_type = models.ForeignKey(
        to='WashType', related_name='orders',
        on_delete=models.PROTECT,
    )

    note = models.TextField(null=True, blank=True, verbose_name=_("Note"))
    price = models.DecimalField(max_digits=4, decimal_places=2, verbose_name=_("Price"))

    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Created date"))
    start_date = models.DateTimeField(verbose_name=_('Scheduled time'))
    end_date = models.DateTimeField(verbose_name=_('End time'), blank=True, null=True)

    def __str__(self):
        return f'{self.car} using {self.wash_type}'

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def save(self, *args, **kwargs):
        if not self.pk:
            self.price = self.car.car_type.price * self.wash_type.percentage / 100
        super(Order, self).save(*args, **kwargs)

back-end/GraeyCarWash/wash/forms.py
from django import forms
from django.core.validators import MaxLengthValidator, MinLengthValidator, RegexValidator
from django.forms import EmailField, CharField, Textarea, ModelChoiceField, TextInput

from wash.models import Order, Car, WashType
from typing import Optional

from wash.validators import validate_phone


class OrderForm(forms.ModelForm):
    note = CharField(widget=Textarea(attrs={
        'id': 'icon_prefix2',
        'class': 'materialize-textarea'
    }), validators=[MaxLengthValidator(150)])
    car = ModelChoiceField(empty_label='აირჩიე მანქანა', queryset=Car.objects.all())
    wash_type = ModelChoiceField(queryset=WashType.objects.all(), empty_label='აირჩიე რეცხვის ტიპი')
    start_date_day = CharField(widget=TextInput(attrs={
        'class': 'datepicker'
    }), validators=[RegexValidator(
        r'^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](21|20)\d\d$',
        message='ფორმატი უნდა იყოს: dd/mm/yyyy'
    )])
    start_date_time = CharField(widget=TextInput(attrs={
        'class': 'timepicker'
    }), validators=[RegexValidator(r'^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$', message='ფორმატი უნდა იყოს: MM:HH')])

    class Meta:
        model = Order
        fields = ('car', 'wash_type', 'note', 'start_date_day', 'start_date_time',)


class ContactForm(forms.Form):
    email = EmailField()
    body = CharField()
    # phone = CharField(validators=[MaxLengthValidator(9), MinLengthValidator(9)])
    phone = CharField(validators=[validate_phone])

    @staticmethod
    def clean_phone(value: Optional[str]):
        '''
            +   995-634-34-34-34
            634343434
        '''
        if value is None:
            return value
        value = value.replace('-', '').strip('+ ')
        return value

back-end/GraeyCarWash/wash/views.py
from datetime import datetime
from decimal import Decimal
from typing import Dict, Optional

from django.core.handlers.wsgi import WSGIRequest
from django.db.models import F, Sum, ExpressionWrapper, DecimalField, Count, Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views.generic import DetailView, FormView
from django.views.generic.edit import FormMixin

from user.models import User
# @TODO: Add Manager Method For Washer Listing
from wash.forms import OrderForm
from wash.models import Order


def washer_list_view(request: WSGIRequest) -> HttpResponse:
    washer_q = Q()
    order_q = Q()
    q = request.GET.get('q')

    if q:
        washer_q &= Q(first_name__icontains=q[-1]) | Q(last_name__icontains=q[-1])
        order_q &= Q(employee__first_name__icontains=q[-1]) | Q(employee__last_name__icontains=q[-1])

    profit_q = ExpressionWrapper(
        F('price') * (1 - F('employee__salary') / Decimal('100.0')),
        output_field=DecimalField()
    )
    order_info: Dict[str, Optional[Decimal]] = Order.objects.filter(end_date__isnull=False).filter(order_q) \
        .annotate(profit_per_order=profit_q) \
        .aggregate(profit=Sum('profit_per_order'), total=Count('id'))

    context = {
        'washers': User.objects.filter(status=User.Status.washer.value).filter(washer_q).annotate(
            washed_count=Count('orders')),
        # **order_info
    }
    context.update(order_info)

    return render(request=request, template_name='wash/washer-list.html', context=context)


# Dispatch (type) -> view

class WasherDetail(DetailView, FormMixin):
    form_class = OrderForm
    template_name='wash/washer-detail.html'
    context_object_name = 'washer'
    queryset = User.objects.filter(status=User.Status.washer)
    model = User

    def get_success_url(self):
        return self.object.get_absolute_url()

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        order_form = self.get_form()
        if order_form.is_valid():
            order: Order = order_form.save(commit=False)
            order.employee_id = self.object.pk
            try:
                start_date = datetime.strptime(
                    " ".join([
                        order_form.cleaned_data['start_date_day'],
                        order_form.cleaned_data['start_date_time']
                    ]),
                    '%d/%m/%Y %H:%M'
                )
                order.start_date = start_date
                order.save()
                return self.form_valid(form=order_form)
            except ValueError:
                order_form.add_error('start_date_day', 'პაპს ნუ ატყუებ')
        return self.form_invalid(form=order_form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        earned_money_q = ExpressionWrapper(
            F('price') * F('employee__salary') / Decimal('100.0'),
            output_field=DecimalField()
        )
        now = timezone.now()
        washer_salary_info: Dict[str, Optional[Decimal]] = self.object.orders.filter(end_date__isnull=False) \
            .annotate(earned_per_order=earned_money_q) \
            .aggregate(
            earned_money_year=Sum(
                'earned_per_order',
                filter=Q(end_date__gte=now - timezone.timedelta(days=365))
            ),
            washed_last_year=Count(
                'id',
                filter=Q(end_date__gte=now - timezone.timedelta(days=365))
            ),
            earned_money_month=Sum(
                'earned_per_order',
                filter=Q(end_date__gte=now - timezone.timedelta(weeks=4))
            ),
            washed_last_month=Count(
                'id',
                filter=Q(end_date__gte=now - timezone.timedelta(weeks=4))
            ),
            earned_money_week=Sum(
                'earned_per_order',
                filter=Q(end_date__gte=now - timezone.timedelta(days=7))
            ),
            washed_last_week=Count(
                'id',
                filter=Q(end_date__gte=now - timezone.timedelta(days=7))
            )
        )
        return {**context, **washer_salary_info}

back-end/GraeyCarWash/templates/wash/contact.html
<form action="." method="post">
    {% csrf_token %}
    {{ contact_form.as_p }}
    <input type="submit" value="Submit">
</form>

back-end/GraeyCarWash/templates/wash/order.html
<form action="." method="post">
    {% csrf_token %}
    {{ order_form.as_p }}
    <input type="submit" value="Submit">
</form>

back-end/GraeyCarWash/templates/wash/save_form.html
<form action="." method="post">
    {% csrf_token %}
    <div>
        <label for="note">Note</label>
        <input type="text" id="note" name="note">
    </div>

    <div>
        <label for="wash_type">Choose a wash type:</label>
        <select id="wash_type" name="wash_type">
            {% for wash_type in wash_types %}
                <option value="{{ wash_type.pk }}">{{ wash_type }}</option>
            {% endfor %}
        </select>
    </div>

    <div>
        <label for="car">Choose a car:</label>
        <select id="car" name="car">
            {% for car in cars %}
                <option value="{{ car.pk }}">{{ car }}</option>
            {% endfor %}
        </select>
    </div>
    <button>Submit</button>
</form>

back-end/GraeyCarWash/templates/wash/washer-detail.html
{% extends 'base.html' %}
{% load user_utilities %}

{% block content %}

    <div class="row">
        <div class="col s12 m7">
            <div class="card">
                <div class="card-image">
                    <img src="{{ washer.image.url }}">
                    {% if washer.first_name %}
                        <span class="card-title">{{ washer.get_full_name }}</span>
                    {% endif %}
                    {% if washer.birthdate|is_adult:16 %}
                        <p> Is adult </p>
                    {% endif %}
                </div>
                <div class="card-content">
                    <p> {{ washer.get_full_name }}</p>
                    <p>I have washed {{ washer.washed_count }}</p>
                </div>
                {#                <div class="card-action">#}
                {#                    <a href="#">Read More</a>#}
                {#                </div>#}
            </div>
        </div>
        <div class="col s12 m5">
            <div class="row">
                <ul class="col s12 collapsible">
                    <li>
                        <div class="collapsible-header">
                            <i class="material-icons">next_week</i>
                            Week
                            <span class="new badge">1</span></div>
                        <div class="collapsible-body">
                            <p>Earned: {{ earned_money_week }}</p>
                            <p>Count: {{ washed_last_week }}</p>

                        </div>
                    </li>
                    <li class="active">
                        <div class="collapsible-header">
                            <i class="material-icons">monetization_on</i>
                            Month
                            <span class="badge">1</span></div>
                        <div class="collapsible-body">
                            <p>Earned: {{ earned_money_month }}</p>
                            <p>Count: {{ washed_last_month }}</p>
                        </div>
                    </li>
                    <li>
                        <div class="collapsible-header">
                            <i class="material-icons">money_off</i>
                            Year
                            <span class="badge">1</span></div>
                        <div class="collapsible-body">
                            <p>Earned: {{ earned_money_year }}</p>
                            <p>Count: {{ washed_last_year }}</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="row">
                {% include 'components/order-form.html' %}
            </div>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.collapsible');
            var instances = M.Collapsible.init(elems, {});
        });


    </script>
{% endblock %}

back-end/GraeyCarWash/templates/wash/washer-list.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12">
                <p> total washed count <strong>{{ total }}</strong></p>

                <p> Profit <strong>{{ profit|default_if_none:0 }} ₾ </strong>
                </p>

            </div>
        </div>
        <div class="row">
            <form class="col s12" method="get" action=".">
{#                {% csrf_token %}#}
                <div class="row">
                    <div class="col s12">
                        Search
                        <div class="input-field inline">
                            <input id="search_washer" type="text" name="q" value="{{ request.GET.q }}">
{#                            <label for="email_inline">Email</label>#}
{#                            <span class="helper-text" data-error="wrong" data-success="right">Helper text</span>#}
                        </div>
                        <button >SEARCH</button>
                    </div>
                </div>
            </form>
        </div>

        {% for washer in washers %}
            {% if forloop.counter0|divisibleby:4 %}
                <div class="row">
            {% endif %}

        <div class="col s12 m3 l3">
            <div class="row">
                <div class="col s12 m7">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{ washer.image.url }}">
                            {#                        <span class="card-title">{{ washer.get_full_name}}</span>#}
                        </div>
                        <div class="card-content">
                            <p> {{ washer.get_full_name }}</p>
                            <p>I have washed {{ washer.washed_count }}</p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'wash:washer-detail' washer.pk %}">Read More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        {% if forloop.counter|divisibleby:4 or forloop.last %}
            </div>
        {% endif %}

        {% endfor %}
    </div>
{% endblock %}