back-end/GraeyCarWash/GraeyCarWash/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('washers/', include('wash.urls', namespace='wash')),
    path('', include('user.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back-end/GraeyCarWash/user/urls.py
# from django.contrib.auth.views import LoginView
from django.urls import path

from user.views import user_registration, user_login, user_logout

app_name = 'user'

urlpatterns = [
    # path('', LoginView.as_view(
    #     template_name='user/login.html'
    # ), name='user_login'),
    path('', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('registration/', user_registration, name='user_registration'),
]

back-end/GraeyCarWash/wash/urls.py
from django.contrib.auth.decorators import login_required as lr
from django.urls import path

from wash.views import washer_list_view, WasherDetail

app_name = 'wash'

urlpatterns = [
    path('', lr(washer_list_view), name='washer-list'),
    path('<int:pk>/', WasherDetail.as_view(), name='washer-detail'),
]

back-end/GraeyCarWash/templates/partials/header.html
<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'wash:washer-list' %}">Washers</a></li>
            {% if user.is_authenticated %}
            <li><span>{{ user.email }}</span></li>
            <li>
                <form action="{% url 'user:user_logout' %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col s12">
                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                გასვლა
{#                                <i class="material-icons right">logout</i>#}
                            </button>
                        </div>
                    </div>
                </form>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'wash:washer-list' %}">Washers</a></li>
</ul>